pipeline {
    agent any

    environment {
        IMAGE_NAME = "petercephas52/chatbot-django"
        CLUSTER_NAME = "chatbot-cluster"
        NAMESPACE = "default"
        DEPLOYMENT_NAME = "chatbot-deployment"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/VenkateshV14/Chat-bot-Ai.git'
            }
        }

        stage('Install Python Requirements & Run Tests') {
            steps {
                steps {
                    sh 'python3 -m pip install --upgrade pip'
                    sh 'python3 -m venv venv'
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-password', variable: 'DOCKER_HUB_PASS')]) {
                    sh '''
                        echo "$DOCKER_HUB_PASS" | docker login -u petercephas52 --password-stdin
                        docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                    aws eks update-kubeconfig --region us-east-1 --name $CLUSTER_NAME
                    kubectl set image deployment/$DEPLOYMENT_NAME chatbot=$IMAGE_NAME -n $NAMESPACE
                '''
            }
        }
    }
}
