pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "petercephas52/chatbot-django"
        AWS_REGION = "us-east-1"
        CLUSTER_NAME = "chatbot-cluster"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/VenkateshV14/Chat-bot-Ai.git'
            }
        }

        stage('Install Python Requirements & Run Tests') {
            steps {
                sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE:latest ."
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                    sh "docker push $DOCKER_IMAGE:latest"
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                script {
                    sh "aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME"
                    sh "kubectl set image deployment/chatbot-deployment chatbot=$DOCKER_IMAGE:latest"
                }
            }
        }
    }
}
