- name: Install kubectl
  hosts: ec2
  become: true
  tasks:
    - name: Get latest stable kubectl version
      shell: "curl -L -s https://dl.k8s.io/release/stable.txt"
      register: kubectl_version_raw

    - name: Debug version being installed
      debug:
        msg: "Installing kubectl version: {{ kubectl_version_raw.stdout }}"

    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version_raw.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"

    - name: Verify kubectl is installed
      command: kubectl version --client
      register: kubectl_version_output

    - name: Show kubectl version
      debug:
        var: kubectl_version_output.stdout
