- name: Install AWS CLI v2
  hosts: ec2
  become: true
  tasks:
    - name: Install unzip
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download AWS CLI v2 installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: Install AWS CLI
      command: ./aws/install
      args:
        chdir: /tmp

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_cli_version

    - name: Show AWS CLI version
      debug:
        var: aws_cli_version.stdout
